### PR TITLE
close #192 パラメータ調整

### LINKED ISSUE #192: ライントレースエリアの調整(Lコース)
## 完了条件
- Lコースのライントレースエリアを9割以上成功する

## 実現方法
- パラメータ調整をする

## 関連資料（省略可）

### PR DESCRIPTION
**Pull request by uchyam**
# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
LineTraceArea.cppのPID、PWM値を変更

# 動作テスト

## 実験データ

- 修正前　

| 番号 | 全体の明るさ | 影の方向 | スポットライトLの明るさ | スポットライトRの明るさ | コース | 走行時間 | 設定ファイル名 |
| ---- | ----------- | ------- | --------------------- | --------------------- | ------ | ------- | ------------- |
| 1 | 2 | 1 | 1 | 1 | Left | 18.533 | sim-settings/l/01.json |
| 2 | 2 | 1 | 1 | 1 | Left | 18.583 | sim-settings/l/02.json |
| 3 | 2 | 1 | 1 | 1 | Left | None | sim-settings/l/03.json |
| 4 | 2 | 1 | 1 | 1 | Left | None | sim-settings/l/04.json |
| 5 | 2 | 1 | 1 | 1 | Left | 19.899 | sim-settings/l/05.json |
| 6 | 2 | 1 | 1 | 1 | Left | 18.449 | sim-settings/l/06.json |
| 7 | 2 | 1 | 1 | 1 | Left | 18.449 | sim-settings/l/07.json |
| 8 | 2 | 1 | 1 | 1 | Left | 18.549 | sim-settings/l/08.json |
| 9 | 2 | 1 | 1 | 1 | Left | 18.449 | sim-settings/l/09.json |
| 10 | 2 | 1 | 1 | 1 | Left | 18.549 | sim-settings/l/10.json |
| 11 | 2 | 1 | 1 | 1 | Right | 18.583 | sim-settings/r/01.json |
| 12 | 2 | 1 | 1 | 1 | Right | 18.483 | sim-settings/r/02.json |
| 13 | 2 | 1 | 1 | 1 | Right | 18.483 | sim-settings/r/03.json |
| 14 | 2 | 1 | 1 | 1 | Right | 18.466 | sim-settings/r/04.json |
| 15 | 2 | 1 | 1 | 1 | Right | 18.466 | sim-settings/r/05.json |
| 16 | 2 | 1 | 1 | 1 | Right | 18.516 | sim-settings/r/06.json |
| 17 | 2 | 1 | 1 | 1 | Right | None | sim-settings/r/07.json |
| 18 | 2 | 1 | 1 | 1 | Right | None | sim-settings/r/08.json |
| 19 | 2 | 1 | 1 | 1 | Right | 18.583 | sim-settings/r/09.json |
| 20 | 2 | 1 | 1 | 1 | Right | None | sim-settings/r/10.json |

- 修正後L

| 番号 | 全体の明るさ | 影の方向 | スポットライトLの明るさ | スポットライトRの明るさ | コース | 走行時間 | 設定ファイル名 |
| ---- | ----------- | ------- | --------------------- | --------------------- | ------ | ------- | ------------- |
| 1 | 2 | 1 | 1 | 1 | Right | 17.266 | sim-settings/r/01.json |
| 2 | 2 | 1 | 1 | 1 | Right | 17.216 | sim-settings/r/02.json |
| 3 | 2 | 1 | 1 | 1 | Right | None | sim-settings/r/03.json |
| 4 | 2 | 1 | 1 | 1 | Right | 17.333 | sim-settings/r/04.json |
| 5 | 2 | 1 | 1 | 1 | Right | None | sim-settings/r/05.json |
| 6 | 2 | 1 | 1 | 1 | Right | 17.299 | sim-settings/r/06.json |
| 7 | 2 | 1 | 1 | 1 | Right | 17.283 | sim-settings/r/07.json |
| 8 | 2 | 1 | 1 | 1 | Right | 17.283 | sim-settings/r/08.json |
| 9 | 2 | 1 | 1 | 1 | Right | 17.166 | sim-settings/r/09.json |
| 10 | 2 | 1 | 1 | 1 | Right | 17.249 | sim-settings/r/10.json |

- 修正後R

| 番号 | 全体の明るさ | 影の方向 | スポットライトLの明るさ | スポットライトRの明るさ | コース | 走行時間 | 設定ファイル名 |
| ---- | ----------- | ------- | --------------------- | --------------------- | ------ | ------- | ------------- |
| 1 | 2 | 1 | 1 | 1 | Right | 17.216 | sim-settings/r/01.json |
| 2 | 2 | 1 | 1 | 1 | Right | 17.249 | sim-settings/r/02.json |
| 3 | 2 | 1 | 1 | 1 | Right | 17.316 | sim-settings/r/03.json |
| 4 | 2 | 1 | 1 | 1 | Right | 17.283 | sim-settings/r/04.json |
| 5 | 2 | 1 | 1 | 1 | Right | 17.216 | sim-settings/r/05.json |
| 6 | 2 | 1 | 1 | 1 | Right | 17.249 | sim-settings/r/06.json |
| 7 | 2 | 1 | 1 | 1 | Right | 17.249 | sim-settings/r/07.json |
| 8 | 2 | 1 | 1 | 1 | Right | 17.183 | sim-settings/r/08.json |
| 9 | 2 | 1 | 1 | 1 | Right | None | sim-settings/r/09.json |
| 10 | 2 | 1 | 1 | 1 | Right | 17.316 | sim-settings/r/10.json |

## 実験結果
- 修正前　

| 走行エリア平均 | 成功率 |
| ------------- | ----- |
| 18.603 [s] (n=15)    | 75.000 [%] (n=20) |

- 修正後L

| 走行エリア平均 | 成功率 |
| ------------- | ----- |
| 17.262 [s] (n=8)    | 80.000 [%] (n=10) |

- 修正後R

| 走行エリア平均 | 成功率 |
| ------------- | ----- |
| 17.253 [s] (n=9)    | 90.000 [%] (n=10) |

- 試走会Lコース

| 走行エリア平均 | 成功率 |
| ------------- | ----- |
|   | 99.500 [%] (n=20) |

### CODE REVIEW

**Comment by arimakaoru** [comment]
Lコースは、試走会の動画20本を確認して、成功率19/20 (99.5%) です！
申請日が2021/09/03 02:03:37 ～ 2021/09/04 09:36:56の動画23本中、Rコースを走行した3本を除く20本

**Review by sugaken0528 — APPROVED** [review]
LGTM

**Review by miyashita64 — APPROVED** [review]
LGTM

**Review by mutotaka0426 — APPROVED** [review]
lgtm

**Review by Takahiro55555 — APPROVED** [review]
LGTM!!!

**Pull request merged**
